(() => {
  const WS = window.WS = {
    token:'', data:null, view:'dashboard', routes:{}, actions:{}, ui:{cart:[],discount:0,selectedLocal:'',dispatch:[],chat:[],productQuery:'',invoiceFilter:'all',accountFilter:'pending'}, commandBusy:false
  };
  WS.$ = selector => document.querySelector(selector);
  WS.$$ = selector => [...document.querySelectorAll(selector)];
  WS.hideBoot = () => { const boot=WS.$('#bootScreen'); if(!boot || boot.classList.contains('is-hidden')) return; boot.classList.add('is-hidden'); setTimeout(()=>boot.remove(),520); };
  WS.esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  WS.money = value => new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(Number(value)||0);
  WS.num = value => new Intl.NumberFormat('es-CO',{maximumFractionDigits:0}).format(Number(value)||0);
  WS.date = value => { const date=new Date(value);return Number.isNaN(date.getTime())?'—':date.toLocaleString('es-CO',{dateStyle:'medium',timeStyle:'short'}) };
  WS.shortDate = value => { const date=new Date(value);return Number.isNaN(date.getTime())?'—':date.toLocaleDateString('es-CO',{day:'2-digit',month:'short',year:'numeric'}) };
  WS.today = () => { const d=new Date(),offset=d.getTimezoneOffset();return new Date(d.getTime()-offset*60000).toISOString().slice(0,10) };
  WS.id = prefix => `${prefix}-${crypto.randomUUID()}`;
  WS.admin = () => WS.data?.session?.role === 'admin';
  WS.cleanError = error => String(error?.message||error||'Ocurrió un error.').replace(/^Error invoking remote method '[^']+': (?:Error: )?/,'').replace(/^Error: /,'');
  // Los cálculos derivados se recalculan solo cuando cambian los datos (cada comando reemplaza WS.data).
  let memo={data:null,values:{}};
  const cached=(name,compute)=>{if(memo.data!==WS.data)memo={data:WS.data,values:{}};if(!Object.hasOwn(memo.values,name))memo.values[name]=compute();return memo.values[name]};
  WS.groups = () => cached('groups',()=>{ const map=new Map();for(const product of WS.data?.products||[]){if(product.active===false)continue;const id=product.pid||product.sku;if(!map.has(id))map.set(id,{pid:id,name:product.name,brand:product.brand,color:product.color,category:product.category,price:product.price,localPrice:product.localPrice,cost:product.cost,image:product.image,sizes:[]});const group=map.get(id);if(!group.image&&product.image)group.image=product.image;group.sizes.push(product)}return [...map.values()] });
  WS.group = pid => WS.groups().find(group=>group.pid===pid);
  WS.invoiceEntries = () => cached('entries',()=>[
    ...(WS.data?.sales||[]).map(invoice=>({type:'sale',invoice,localName:'Venta directa'})),
    ...(WS.data?.closures||[]).map(invoice=>({type:'closure',invoice,localName:invoice.localName||'Local archivado'}))
  ].sort((a,b)=>new Date(b.invoice.date)-new Date(a.invoice.date)));
  WS.account = (type,id) => cached('accounts',()=>new Map((WS.data?.accounts||[]).map(account=>[`${account.documentType}:${account.documentId}`,account]))).get(`${type}:${id}`);
  WS.media = (image,name,className='') => image?`<img class="${className}" src="${WS.esc(image)}" alt="${WS.esc(name)}">`:`<div class="media-fallback ${className}">${WS.esc(String(name||'W').trim().slice(0,2).toUpperCase())}</div>`;
  WS.empty = (icon,title,text,action='') => `<div class="empty-state"><div class="empty-icon">${icon}</div><b>${WS.esc(title)}</b><p>${WS.esc(text)}</p>${action}</div>`;
  WS.statusBadge = (label,tone='neutral') => `<span class="badge ${tone}">${WS.esc(label)}</span>`;

  WS.toast = (title,detail='',tone='success',sticky=false) => {
    const toast=document.createElement('div');toast.className=`toast ${tone}`;toast.innerHTML=`<div><b>${WS.esc(title)}</b>${detail?`<span>${WS.esc(detail)}</span>`:''}</div>`;WS.$('#toastStack').appendChild(toast);
    if(!sticky)setTimeout(()=>{toast.style.opacity='0';toast.style.transform='translateX(12px)';setTimeout(()=>toast.remove(),180)},3600);
    return toast;
  };

  WS.schedule = () => { const settings=WS.data?.settings||{},now=new Date(),days=settings.workDays||[1,2,3,4,5,6],[oh,om]=String(settings.openTime||'09:00').split(':').map(Number),[ch,cm]=String(settings.closeTime||'18:00').split(':').map(Number),minutes=now.getHours()*60+now.getMinutes();return{open:settings.enforceSchedule===false||(days.includes(now.getDay())&&minutes>=oh*60+om&&minutes<ch*60+cm),enforced:settings.enforceSchedule!==false,openTime:settings.openTime||'09:00',closeTime:settings.closeTime||'18:00'} };
  WS.syncChrome = () => {
    const data=WS.data;if(!data)return;WS.$('#brandName').textContent='WannaShop';WS.$('#userName').textContent=data.session.name;WS.$('#userRole').textContent=WS.admin()?'Administrador':'Operador';WS.$('#userAvatar').textContent=(data.session.name||'W').slice(0,2).toUpperCase();
    WS.$$('[data-admin-block]').forEach(element=>element.classList.toggle('hidden',!WS.admin()));WS.$$('#mainNav [data-view]').forEach(button=>button.classList.toggle('active',button.dataset.view===WS.view));
    const schedule=WS.schedule(),pill=WS.$('#schedulePill');pill.className=`schedule-pill ${schedule.open?'':'closed'}`;pill.textContent=schedule.open?`Abierto · ${schedule.closeTime}`:`Cerrado · abre ${schedule.openTime}`;
    const context=WS.$('#contextBar');context.classList.toggle('hidden',schedule.open||!schedule.enforced);context.textContent=`Bodega cerrada · Puedes consultar. Un administrador puede autorizar una excepción con motivo.`;
    const external=data.protection?.external,orb=WS.$('#protectionOrb');orb.classList.toggle('warn',!external?.configured||external?.ok===false);WS.$('#protectionTitle').textContent=external?.configured?(external.ok===false?'Revisar respaldo':'Doble protección'):'Protección local';WS.$('#protectionText').textContent=external?.configured?(external.ok===false?'La segunda copia falló':'Local + segunda carpeta'):'Configura una segunda carpeta';
    if(data.protection?.cloud){WS.$('#protectionTitle').textContent='En la nube';WS.$('#protectionText').textContent=data.protection.cloud}
    const pending=(data.accounts||[]).filter(a=>!a.unreconciled&&a.balance>0).length,count=WS.$('#debtCount');count.textContent=pending;count.classList.toggle('hidden',!pending);
  };

  WS.titles={cash:['CUADRE DIARIO','Caja del día'],expenses:['CONTROL DE COSTOS','Gastos'],dashboard:['OPERACIÓN EN TIEMPO REAL','Centro de control'],inventory:['CATÁLOGO POR MODELOS','Inventario'],sale:['FACTURACIÓN SEGURA','Venta rápida'],businesses:['RED DE CONSIGNACIÓN','Negocios asociados'],accounts:['CONTROL DE CARTERA','Cobros y saldos'],invoices:['DOCUMENTOS Y CORRECCIONES','Facturas'],consolidated:['CIERRE DE OPERACIÓN','Consolidado'],settings:['CENTRO DE CONTROL','Configuración'],purchases:['ENTRADAS CON COSTO HISTÓRICO','Compras'],suppliers:['DIRECTORIO PRIVADO','Proveedores'],customers:['RELACIONES COMERCIALES','Clientes'],reports:['INFORMACIÓN PRIVADA','Rentabilidad'],history:['TRAZABILIDAD COMPLETA','Historial']};
  WS.render = (view=WS.view) => {
    if(!WS.data)return;view=WS.routes[view]?view:'dashboard';if(!WS.admin()&&['purchases','suppliers','reports','history','settings','expenses'].includes(view))view='dashboard';WS.view=view;const [eyebrow,title]=WS.titles[view]||['WANNASHOP','WannaShop'];WS.$('#pageEyebrow').textContent=eyebrow;WS.$('#pageTitle').textContent=title;WS.syncChrome();const app=WS.$('#app');app.style.animation='none';void app.offsetWidth;app.style.animation='';WS.routes[view]();app.focus({preventScroll:true});
  };
  WS.navigate = view => { WS.closeDrawer();WS.render(view) };
  WS.reload = async () => { WS.data=await window.api.load(WS.token);WS.syncChrome();return WS.data };

  WS.modal = (html,{wide=false,onOpen}={}) => { const modal=WS.$('#modal'),panel=modal.querySelector('.modal-panel');panel.classList.toggle('wide',wide);WS.$('#modalBody').innerHTML=html;modal.classList.remove('hidden');setTimeout(()=>{const first=modal.querySelector('input:not([type=hidden]),select,textarea,button');first?.focus();onOpen?.()},0) };
  WS.closeModal = () => { WS.$('#modal').classList.add('hidden');WS.$('#modalBody').innerHTML='' };
  WS.drawer = html => { WS.$('#drawerBody').innerHTML=html;WS.$('#drawer').classList.remove('hidden') };
  WS.closeDrawer = () => { WS.$('#drawer').classList.add('hidden');WS.$('#drawerBody').innerHTML='' };
  WS.confirm = ({title,message,confirmText='Confirmar',danger=false,requireText=''}) => new Promise(resolve => {
    WS.modal(`<h2 id="modalTitle">${WS.esc(title)}</h2><p class="modal-subtitle">${WS.esc(message)}</p>${requireText?`<label class="field">${WS.esc(requireText)}<textarea id="confirmReason" required></textarea></label>`:''}<div class="form-actions"><button class="secondary" id="confirmCancel">Cancelar</button><button class="${danger?'danger':'primary'}" id="confirmOk">${WS.esc(confirmText)}</button></div>`,{onOpen:()=>{WS.$('#confirmCancel').onclick=()=>{WS.closeModal();resolve(false)};WS.$('#confirmOk').onclick=()=>{const reason=WS.$('#confirmReason')?.value.trim()||'';if(requireText&&reason.length<5)return WS.toast('Explica el motivo','Escribe al menos 5 caracteres.','warning');WS.closeModal();resolve(requireText?reason:true)}}});
  });
  WS.prompt = ({title,message,label,placeholder='',type='text',value=''}) => new Promise(resolve => {
    WS.modal(`<h2 id="modalTitle">${WS.esc(title)}</h2><p class="modal-subtitle">${WS.esc(message)}</p><label class="field">${WS.esc(label)}<input id="promptValue" type="${WS.esc(type)}" value="${WS.esc(value)}" placeholder="${WS.esc(placeholder)}"></label><div class="form-actions"><button class="secondary" id="promptCancel">Cancelar</button><button class="primary" id="promptOk">Continuar</button></div>`,{onOpen:()=>{WS.$('#promptCancel').onclick=()=>{WS.closeModal();resolve(null)};WS.$('#promptOk').onclick=()=>{const value=WS.$('#promptValue').value.trim();if(!value)return WS.toast('Completa el campo','','warning');WS.closeModal();resolve(value)}}});
  });

  WS.command = async (type,payload={},options={}) => {
    if(WS.commandBusy){WS.toast('Operación en curso','Espera un momento para evitar duplicados.','warning');return null}
    WS.commandBusy=true;const operationId=WS.id('OP'),command={type,payload,operationId,expectedRevision:WS.data.meta.revision};
    try{
      let response;
      try{response=await window.api.command(WS.token,command)}catch(error){
        const message=WS.cleanError(error);
        if(/bodega está cerrada/i.test(message)&&WS.admin()&&!options.noOverride){const reason=await WS.prompt({title:'Autorizar fuera de horario',message:'Esta excepción quedará registrada con tu usuario.',label:'Motivo de la excepción',placeholder:'Ej. inventario urgente autorizado'});if(!reason)throw error;response=await window.api.command(WS.token,{...command,overrideSchedule:true,overrideReason:reason})}else throw error;
      }
      WS.data=response.data;WS.syncChrome();if(response.backup?.ok===false)WS.toast('Movimiento guardado, respaldo incompleto','Abre Protección para revisar la segunda copia.','warning',true);else WS.toast(options.success||'Operación guardada',options.detail||WS.savedDetail||'Copia automática verificada.');return response.result;
    }catch(error){const message=WS.cleanError(error);if(/información cambió/i.test(message))await WS.reload();WS.toast('No se pudo completar',message,'error',true);return null}finally{WS.commandBusy=false}
  };

  WS.compressImage = file => new Promise((resolve,reject) => { if(!file)return resolve('');if(file.size>12*1024*1024)return reject(new Error('La imagen supera 12 MB.'));const reader=new FileReader();reader.onerror=()=>reject(new Error('No se pudo leer la imagen.'));reader.onload=()=>{const image=new Image();image.onerror=()=>reject(new Error('El archivo no es una imagen válida.'));image.onload=()=>{const max=1000,scale=Math.min(1,max/Math.max(image.width,image.height)),canvas=document.createElement('canvas');canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',.84))};image.src=reader.result};reader.readAsDataURL(file) });
  WS.bindPhoto = (inputSelector,previewSelector,onImage) => { const input=WS.$(inputSelector),preview=WS.$(previewSelector);if(!input)return;input.onchange=async()=>{try{const image=await WS.compressImage(input.files[0]);onImage(image);preview.src=image;preview.classList.remove('hidden')}catch(error){WS.toast('No se pudo usar la foto',WS.cleanError(error),'error')}} };

  WS.actions.closeModal=WS.closeModal;WS.actions.closeDrawer=WS.closeDrawer;WS.actions.openPalette=()=>WS.openPalette();
  WS.actions.copyText=(_,data)=>{try{navigator.clipboard.writeText(data.text||'')}catch(e){}WS.toast('Copiado')};
  WS.actions.quickCreate=()=>{const admin=WS.admin();WS.modal(`<h2 id="modalTitle">Crear nuevo</h2><p class="modal-subtitle">Elige una acción rápida.</p><div class="quick-grid"><button class="quick-card" data-view="sale"><i>◇</i><b>Venta</b><small>Factura segura</small></button><button class="quick-card" data-view="businesses"><i>▤</i><b>Despacho</b><small>A un negocio</small></button><button class="quick-card" data-view="accounts"><i>◎</i><b>Abono</b><small>Registrar cobro</small></button>${admin?'<button class="quick-card" data-action="newProduct"><i>▦</i><b>Producto</b><small>Modelo y tallas</small></button>':''}</div>`)};
  WS.actions.userMenu=()=>{const admin=WS.admin();WS.modal(`<h2 id="modalTitle">${WS.esc(WS.data.session.name)}</h2><p class="modal-subtitle">Sesión ${admin?'de administrador':'de operador'} · Los datos sensibles ${admin?'están disponibles solo aquí.':'permanecen ocultos.'}</p><div class="form-actions"><button class="secondary" data-action="changePassword">Cambiar contraseña</button>${admin?'<button class="secondary" data-action="staff">Usuarios</button>':''}<button class="danger" data-action="logout">Bloquear sesión</button></div>`)};
  WS.actions.logout=async()=>{await window.api.logout(WS.token);WS.token='';WS.data=null;WS.$('#shell').classList.add('hidden');WS.$('#authRoot').classList.remove('hidden');WS.closeModal();showLogin()};
  WS.actions.changePassword=()=>{WS.modal(`<h2 id="modalTitle">Cambiar contraseña</h2><p class="modal-subtitle">La nueva contraseña cerrará las demás sesiones.</p><form id="passwordForm"><div class="form-grid"><label class="field span-2">Contraseña actual<input name="currentPassword" type="password" required></label><label class="field">Nueva contraseña<input name="newPassword" type="password" minlength="6" required></label><label class="field">Repetir contraseña<input name="confirm" type="password" minlength="6" required></label></div><div class="form-actions"><button type="button" class="secondary" data-action="closeModal">Cancelar</button><button class="primary">Actualizar</button></div></form>`,{onOpen:()=>{WS.$('#passwordForm').onsubmit=async event=>{event.preventDefault();const form=Object.fromEntries(new FormData(event.currentTarget));if(form.newPassword!==form.confirm)return WS.toast('Las contraseñas no coinciden','','warning');try{await window.api.changePassword(WS.token,form);WS.closeModal();WS.toast('Contraseña actualizada')}catch(error){WS.toast('No se pudo cambiar',WS.cleanError(error),'error')}}}})};

  function authLayout(title,subtitle,fields,button){return `<div class="auth-card"><div class="auth-brand"><img src="assets/wannashop-logo.png" alt="Logo WannaShop"><h1>${WS.esc(title)}</h1><p>${WS.esc(subtitle)}</p></div><form id="authForm">${fields}<div id="authError" class="error-box hidden"></div><button class="primary button" id="authSubmit">${WS.esc(button)}</button></form><p class="auth-foot">WannaShop · Información protegida en este equipo</p></div>`}
  function showSetup(){WS.$('#authRoot').innerHTML=authLayout('Protege tu bodega','Crea la cuenta del dueño. No existe contraseña predeterminada.',`<label class="field">Tu nombre<input name="name" autocomplete="name" required placeholder="Nombre del administrador"></label><label class="field">Usuario<input name="username" autocomplete="username" pattern="[A-Za-z0-9._-]{3,30}" required placeholder="Ej. administrador"></label><div class="form-grid"><label class="field">Contraseña<input name="password" type="password" minlength="6" autocomplete="new-password" required></label><label class="field">Repetir<input name="confirm" type="password" minlength="6" autocomplete="new-password" required></label></div>`,'Crear cuenta segura');bindAuth(true);WS.hideBoot()}
  function showLogin(){WS.$('#authRoot').innerHTML=authLayout('Bienvenido de nuevo','Ingresa para continuar con tu bodega.',`<label class="field">Usuario<input name="username" autocomplete="username" required autofocus></label><label class="field">Contraseña<input name="password" type="password" autocomplete="current-password" required></label>`,'Entrar a WannaShop');bindAuth(false);const foot=WS.$('.auth-foot');if(foot)foot.insertAdjacentHTML('beforebegin','<button type="button" class="link-button auth-link" id="toRecover">¿Olvidaste tu contraseña?</button>');const link=WS.$('#toRecover');if(link)link.onclick=showRecover;WS.hideBoot()}
  async function enterShell(){WS.data=await window.api.load(WS.token);WS.$('#authRoot').classList.add('hidden');WS.$('#shell').classList.remove('hidden');WS.render('dashboard');WS.hideBoot()}
  function showRecoveryScreen(code,onContinue){WS.$('#authRoot').classList.remove('hidden');WS.$('#authRoot').innerHTML=`<div class="auth-card"><div class="auth-brand"><img src="assets/wannashop-logo.png" alt="Logo WannaShop"><h1>Guarda tu código de recuperación</h1><p>Es la única forma de recuperar el acceso si olvidas tu contraseña. Anótalo en un lugar seguro; no volveremos a mostrarlo.</p></div><div class="recovery-code">${WS.esc(code)}</div><div class="form-actions" style="justify-content:center;gap:10px"><button type="button" class="secondary" id="copyRecovery">Copiar código</button><button type="button" class="primary" id="recoveryContinue">Ya lo guardé, continuar</button></div><p class="auth-foot">Podrás renovarlo cuando quieras desde Configuración.</p></div>`;WS.$('#copyRecovery').onclick=()=>{try{navigator.clipboard.writeText(code)}catch(e){}WS.toast('Código copiado')};WS.$('#recoveryContinue').onclick=onContinue;WS.hideBoot()}
  function showRecover(){WS.$('#authRoot').innerHTML=authLayout('Recuperar acceso','Escribe tu usuario de administrador, el código de recuperación y una nueva contraseña.',`<label class="field">Usuario<input name="username" autocomplete="username" required></label><label class="field">Código de recuperación<input name="recoveryCode" required placeholder="XXXX-XXXX-XXXX-XXXX"></label><div class="form-grid"><label class="field">Nueva contraseña<input name="newPassword" type="password" minlength="6" required></label><label class="field">Repetir<input name="confirm" type="password" minlength="6" required></label></div>`,'Restablecer contraseña');const foot=WS.$('.auth-foot');if(foot)foot.insertAdjacentHTML('beforebegin','<button type="button" class="link-button auth-link" id="toLogin">Volver a iniciar sesión</button>');WS.$('#toLogin').onclick=showLogin;WS.$('#authForm').onsubmit=async event=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget)),button=WS.$('#authSubmit'),errorBox=WS.$('#authError');if(values.newPassword!==values.confirm){errorBox.textContent='Las contraseñas no coinciden.';errorBox.classList.remove('hidden');return}button.classList.add('loading');button.disabled=true;try{const result=await window.api.recover(values);showRecoveryScreen(result.recoveryCode,showLogin)}catch(error){errorBox.textContent=WS.cleanError(error);errorBox.classList.remove('hidden')}finally{button.classList.remove('loading');button.disabled=false}};WS.hideBoot()}
  function bindAuth(setup){WS.$('#authForm').onsubmit=async event=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget)),button=WS.$('#authSubmit'),errorBox=WS.$('#authError');if(setup&&values.password!==values.confirm){errorBox.textContent='Las contraseñas no coinciden.';errorBox.classList.remove('hidden');return}button.classList.add('loading');button.disabled=true;try{const result=setup?await window.api.setupOwner(values):await window.api.login(values);WS.token=result.token;if(setup&&result.recoveryCode)showRecoveryScreen(result.recoveryCode,enterShell);else await enterShell()}catch(error){errorBox.textContent=WS.cleanError(error);errorBox.classList.remove('hidden');WS.hideBoot()}finally{button.classList.remove('loading');button.disabled=false}}}

  WS.paletteItems = () => {
    const routes=[['dashboard','⌂','Centro de control','Resumen y alertas'],['inventory','▦','Inventario','Modelos, tallas y stock'],['sale','◇','Nueva venta','Crear una factura'],['businesses','▤','Negocios asociados','Despachos y cierres'],['accounts','◎','Cobros y saldos','Cartera pendiente'],['cash','◫','Caja del día','Cuadre de efectivo'],['invoices','▧','Facturas','PDF, Excel, devoluciones y cambios'],['consolidated','Σ','Consolidado','Cierre por fecha y local']];
    if(WS.admin())routes.push(['expenses','⇡','Gastos','Arriendo, transporte y nómina'],['settings','⚙','Configuración','Negocio, horario y copias'],['purchases','⇣','Compras','Entradas y costos'],['suppliers','♧','Proveedores','Directorio privado'],['customers','♙','Clientes','Contactos y fotos'],['reports','↗','Rentabilidad','Información privada'],['history','≡','Historial','Auditoría']);
    const items=routes.map(([view,icon,title,subtitle])=>({icon,title,subtitle,run:()=>WS.navigate(view)}));
    for(const group of WS.groups())items.push({icon:'▦',title:group.name,subtitle:`Producto · ${group.sizes.map(s=>s.size).join(', ')}`,run:()=>{WS.ui.productQuery=group.name;WS.navigate('inventory')}});
    for(const local of (WS.data.locales||[]).filter(l=>l.active!==false))items.push({icon:'▤',title:local.name,subtitle:'Negocio asociado',run:()=>{WS.ui.selectedLocal=local.id;WS.navigate('businesses')}});
    for(const {type,invoice} of WS.invoiceEntries().slice(0,50))items.push({icon:'▧',title:invoice.number,subtitle:`Factura · ${invoice.customer?.name||'Consumidor final'}`,run:()=>WS.actions.invoiceDetail(null,{type,id:invoice.id})});
    return items;
  };
  WS.openPalette = () => {WS.$('#palette').classList.remove('hidden');const input=WS.$('#paletteInput');input.value='';renderPalette('');setTimeout(()=>input.focus(),0)};
  WS.closePalette = () => WS.$('#palette').classList.add('hidden');
  function renderPalette(query){const q=String(query||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,''),items=WS.paletteItems().filter(item=>`${item.title} ${item.subtitle}`.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').includes(q)).slice(0,40);WS.ui.paletteItems=items;WS.$('#paletteResults').innerHTML=items.length?items.map((item,index)=>`<button class="palette-item ${index===0?'selected':''}" data-palette-index="${index}"><span class="palette-item-icon">${item.icon}</span><span><b>${WS.esc(item.title)}</b><small>${WS.esc(item.subtitle)}</small></span><span>↵</span></button>`).join(''):WS.empty('⌕','Sin resultados','Prueba otra palabra.')}

  document.addEventListener('click',event=>{
    const view=event.target.closest('[data-view]');if(view){WS.closeModal();WS.closePalette();WS.navigate(view.dataset.view);return}
    const palette=event.target.closest('[data-palette-index]');if(palette){const item=WS.ui.paletteItems?.[Number(palette.dataset.paletteIndex)];if(item){WS.closePalette();item.run()}return}
    const button=event.target.closest('[data-action]');if(button){const action=WS.actions[button.dataset.action];if(action)action(button,button.dataset);return}
    if(event.target.id==='modal')WS.closeModal();if(event.target.id==='palette')WS.closePalette();
  });
  document.addEventListener('keydown',event=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='k'){event.preventDefault();WS.$('#palette').classList.contains('hidden')?WS.openPalette():WS.closePalette()}if(event.key==='Escape'){WS.closePalette();WS.closeDrawer();if(!WS.$('#modal').classList.contains('hidden'))WS.closeModal()}});
  WS.$('#paletteInput').addEventListener('input',event=>renderPalette(event.target.value));
  WS.$('#paletteInput').addEventListener('keydown',event=>{const items=WS.$$('.palette-item');let index=items.findIndex(item=>item.classList.contains('selected'));if(event.key==='ArrowDown'||event.key==='ArrowUp'){event.preventDefault();items[index]?.classList.remove('selected');index=event.key==='ArrowDown'?Math.min(items.length-1,index+1):Math.max(0,index-1);items[index]?.classList.add('selected');items[index]?.scrollIntoView({block:'nearest'})}if(event.key==='Enter'&&index>=0){event.preventDefault();items[index].click()}});
  setInterval(()=>{if(WS.data)WS.syncChrome()},60000);
  WS.authLayout=authLayout;WS.enterShell=enterShell;
  // La versión web carga su puente (window.api) como módulo: se arranca cuando todo el documento está listo.
  const start=async()=>{let timeout;try{const authStatus=window.api.authStatus(),status=await(window.api?.web?Promise.race([authStatus,new Promise((_,reject)=>{timeout=setTimeout(()=>reject(new Error('La verificación de inicio está tardando demasiado. Comprueba tu conexión y vuelve a intentarlo.')),12000)})]):authStatus);if(status.web)return WS.webAuth(status);status.needsSetup?showSetup():showLogin()}catch(error){const message=WS.cleanError(error);if(window.api?.web&&WS.webAuth){WS.webAuth({web:true,cloudAvailable:true,error:message,retryable:true});return}WS.$('#authRoot').innerHTML=authLayout('No se pudo iniciar',message,'','Reintentar');const form=WS.$('#authForm');if(form)form.onsubmit=event=>{event.preventDefault();start()};WS.hideBoot()}finally{clearTimeout(timeout)}};
  document.readyState==='loading'?document.addEventListener('DOMContentLoaded',start):start();
})();
